newSite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static # < this
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webBlog.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # < this
    

webBlog/urls.py
from django.urls import path
from . import views

app_name = 'webBlog'
urlpatterns = [
    path('', views.index, name='index'),
    path('band/', views.band, name='band'),
    path('tour/', views.tour, name='tour'),
    path('contact/', views.contact, name='contact'),
    
    path('blog/', views.BlogListView.as_view(), name='blog'),
    
    path('polls/', views.IndexView.as_view(), name='polls-index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

webBlog/models.py
from django.db import models
from imagekit.models import ImageSpecField # < import this
from imagekit.processors import ResizeToFill # < import this
from django.utils import timezone
from datetime import datetime, date, time, timedelta

class Post(models.Model):
    image = models.ImageField(upload_to="post_images") # Regular image field
    title = models.CharField(max_length=200)
    body = models.TextField()
    signature = models.CharField(max_length=140, default= 'JR')
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,)
    created_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.title
    

class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timedelta(days=1)

webBlog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views.generic import ListView

from . models import Post
from .models import Choice, Question
# main views

def index(request):
  return render(request, 'webBlog/index.html')

def band(request):
  return render(request, 'webBlog/band.html')

def tour(request):
  return render(request, 'webBlog/tour.html')

def contact(request):
  return render(request, 'webBlog/contact.html')

# blog views

class BlogListView(ListView):
    model = Post
    template_name = 'blog.html'

    def get_queryset(self):
        """
        Return the last five published posts
        """
        return Post.objects.filter(
            created_date__lte=timezone.now()
        ).order_by('-created_date')[:5]


# poll views

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('webBlog:results', args=(question.id,)))

blog/templates/header.html
{%load staticfiles%}



<!DOCTYPE html>
<html lang="en">
<head>

  <title>The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>


<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#myPage">The Band </a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        
        <li><a href="{% url 'index' %}">HOME</a></li>
        <li><a href="{% url 'band' %}">BAND</a></li>
        <li><a href="{% url 'tour' %}">TOUR</a></li>
        <li><a href="{% url 'contact' %}">CONTACT</a></li>
        <li><a href="{% url 'blog:header' %}" >BLOG</a><li>
        <li><a href="{% url 'polls:index' %}" >POLLS </a><li>

     </ul>
      </div>
  </div>
</nav>

<br>
</br>
<br>
</br>

<new class="text-center">
 <h3> The Band Blog </h3>
 
<div class="container">
      {% block content %}
      {% endblock content %}
  </div>

</div>


</new>




<footer class="text-center">
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p> &copy; Jordan Roberts.&nbsp;&nbsp; All Rights Reserved.&nbsp;&nbsp; Proudly created by Jordan Roberts</p>
</footer>
 
<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip(); 
  
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

</body>



</html>

webBlog/templates/blog.html
{% extends 'header.html' %}

{% block content %}
  {% for post in object_list %}
   
<hr color= "#505050" style="height:10px">
<br>

    <div class="post-entry">
      <h3>{{ post.title }}</h3>
     <img class="img-responsive center-block" class="post__image__img" src="/media/{{ post.image }}">
     <br><br>
     <p> Added on: {{ post.created_date }}</p>
      <p>{{ post.body }}</p>
      <p>BY {{ post.signature }}</p>

  </div>

<br>
</br>


  {% endfor %}
{% endblock content %}

webBlog/templates/header.html
{%load staticfiles%}



<!DOCTYPE html>
<html lang="en">
<head>

  <title>The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>


<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">The Band </a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'webBlog:index' %}">HOME</a></li>
        <li><a href="{% url 'webBlog:band' %}">BAND</a></li>
        <li><a href="{% url 'webBlog:tour' %}">TOUR</a></li>
        <li><a href="{% url 'webBlog:contact' %}">CONTACT</a></li>
        <li><a href="{% url 'webBlog:blog' %}" >BLOG</a>
        <li><a href="{% url 'webBlog:polls-index' %}" >POLLS </a>

     </ul>
      </div>
  </div>
</nav>

<br>
</br>
<br>
</br>

<new class="text-center">
 <h3> The Band Blog </h3>

<div class="container">
      {% block content %}
      {% endblock content %}
  </div>

</div>


</new>





<footer class="text-center" >
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p> &copy; Jordan Roberts</p>
</footer>


<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip();

  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

</body>



</html>

webBlog/templates/polls/detail.html
{%load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>


<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">


<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">The Band </a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'webBlog:index' %}">HOME</a></li>
        <li><a href="{% url 'webBlog:band' %}">BAND</a></li>
        <li><a href="{% url 'webBlog:tour' %}">TOUR</a></li>
        <li><a href="{% url 'webBlog:contact' %}">CONTACT</a></li>
        <li><a href="{% url 'webBlog:blog' %}" >BLOG</a>
        <li><a href="{% url 'webBlog:polls-index' %}" >POLLS </a>

     </ul>
      </div>
  </div>
  </nav>

<br>
</br>
<br>
</br>


<
<new class= "text-center">

<h3>{{ question.question_text }}</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'webBlog:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<br>
</br>
<input type="submit" value="Vote" />
</form>
</div>

</new>



<div class="footer navbar-fixed-bottom">
<footer class="text-center" >
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p> &copy; Jordan Roberts</p>
</footer>

</div>

<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip();

  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

</body>
</html>

webBlog/templates/polls/index.html
{%load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>


<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">The Band </a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'webBlog:index' %}">HOME</a></li>
        <li><a href="{% url 'webBlog:band' %}">BAND</a></li>
        <li><a href="{% url 'webBlog:tour' %}">TOUR</a></li>
        <li><a href="{% url 'webBlog:contact' %}">CONTACT</a></li>
        <li><a href="{% url 'webBlog:blog' %}" >BLOG</a>
        <li><a href="{% url 'webBlog:polls-index' %}" >POLLS </a>

     </ul>
      </div>
  </div>
  </nav>

<br>
</br>
<br>
</br>


<new class= "text-center">

<h3> Welcome to the Polls! </h3>


{% if latest_question_list %}
    <ul class= "list-unstyled" >
    {% for question in latest_question_list %}
        <li><br><a href="{% url 'webBlog:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


</new>

<div class="footer navbar-fixed-bottom">
<footer class="text-center" >
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p> &copy; Jordan Roberts</p>
</footer>

</div>

<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip();

  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>
</body>
</html>

webBlog/templates/polls/results.html
{%load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>


<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">


<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">The Band </a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'webBlog:index' %}">HOME</a></li>
        <li><a href="{% url 'webBlog:band' %}">BAND</a></li>
        <li><a href="{% url 'webBlog:tour' %}">TOUR</a></li>
        <li><a href="{% url 'webBlog:contact' %}">CONTACT</a></li>
        <li><a href="{% url 'webBlog:blog' %}" >BLOG</a>
        <li><a href="{% url 'webBlog:polls-index' %}" >POLLS </a>

     </ul>
      </div>
  </div>
  </nav>

<br>
</br>
<br>
</br>

<new class = "text-center">
<h3>{{ question.question_text }}</h3>

<ul class="list-unstyled">
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>



<p><a href="{% url 'webBlog:detail' question.id %}">Vote again?</a>
 </p>

 </new>




 <div class="footer navbar-fixed-bottom">
 <footer class="text-center" >
   <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
     <span class="glyphicon glyphicon-chevron-up"></span>
   </a>
   <p> &copy; Jordan Roberts</p>
 </footer>

 </div>

<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip();

  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

</body>
</html>

webBlog/templates/webBlog/band.html
{%load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>The Band - The Musicians</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<head>
 <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">The Band </a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'webBlog:index' %}">HOME</a></li>
        <li><a href="{% url 'webBlog:band' %}">BAND</a></li>
        <li><a href="{% url 'webBlog:tour' %}">TOUR</a></li>
        <li><a href="{% url 'webBlog:contact' %}">CONTACT</a></li>
        <li><a href="{% url 'webBlog:blog' %}" >BLOG</a>
        <li><a href="{% url 'webBlog:polls-index' %}" >POLLS </a>

     </ul>
      </div>
  </div>
  </nav>

<!-- Container (The Band Section) -->
<div id="band" class="container text-center">
  <h3>THE BAND</h3>
  <p><em>We love music!</em></p>
  <p> Welcome to our Website! We hope you enjoy and get a chance to see us perform.
  	Behaviour we improving at something to. Evil true high lady roof men had open. To projection considered it precaution an melancholy or. Wound young you thing worse along being ham. Dissimilar of favourable solicitude if sympathize middletons at. Forfeited up if disposing perfectly in an eagerness perceived necessary. Belonging sir curiosity discovery extremity yet forfeited prevailed own off. Travelling by introduced of mr terminated. Knew as miss my high hope quit. In curiosity shameless dependent knowledge up.

  </p>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <p class="text-center"><strong>Greg White</strong></p><br>
      <a href="#demo" data-toggle="collapse">
        <img src="{%static "assets/head1.jpg" %}" class="img-circle person" alt="Random Name" width="255" height="255">
      </a>
      <div id="demo" class="collapse">
        <p>Guitarist and Lead Vocalist</p>
        <p>I surf 24/7 in my free time.</p>
        <p>Member since 2010</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Dave Shipper</strong></p><br>
      <a href="#demo2" data-toggle="collapse">
        <img src="{%static "assets/head2.jpg" %}" class="img-circle person" alt="Random Name" width="255" height="255">
      </a>
      <div id="demo2" class="collapse">
        <p>Drummer</p>
        <p>Walks the runway and can keep a beat.</p>
        <p>Member since 2010</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>John Doe</strong></p><br>
      <a href="#demo3" data-toggle="collapse">
        <img src="{%static "assets/head3.jpg" %}" class="img-circle person" alt="Random Name" width="255" height="255">
      </a>
      <div id="demo3" class="collapse">
        <p>Bass player</p>
        <p>I also love catching Bass! </p>
        <p>Member since 2015</p>
      </div>
    </div>
  </div>
</div>


<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip();

  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

</body>


<footer class="text-center" >
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p> &copy; Jordan Roberts</p>
</footer>



</html>